### PR TITLE
fix qvector memory leak

### PR DESCRIPTION
**Pull request by SunBeau**
Add "free(vector->data);" in qvector_free()

### CODE REVIEW

**Comment by SunBeau** [comment]
My editor automatically deleted useless spaces

**Comment by wolkykim** [comment]
Thanks for the fix. It'd be a bit unclear in the commit log what's actually changed.
Could you make a PR with 2 commits. 1 that removes unnecessary spaces and the other that fixes the code to make the commit logs easier to understand?

**Comment by SunBeau** [comment]
I make a new PR. you can check it.

**Comment by wolkykim** [comment]
#76 replace this PR. closing

**Pull request closed without merging**
