### PR TITLE
fix cmake error on centos

### PR DESCRIPTION
**Pull request by SunBeau**
Fix the error as shown below, when executing cmake on centos7
CMake Error

### CODE REVIEW

**Review by wolkykim — APPROVED** [review]

**Comment by SunBeau** [comment]
I have added and passed the multi-platform test

**Comment by wolkykim** [comment]
Thank you

**Comment by wolkykim** [comment]
Just a few questions before merging in.

- I see this warning message. Is this something addressable easily?
"Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/."

- Do we need to run multiple tests per each version of OS? like ubuntu-2004, ubuntu-1804, ... Or is it ok to run the test on the latest version only? Like 1 test per OS except it's necessary?

- Can Windows be included in the test?

**Comment by SunBeau** [comment]
- I solved the warning by upgrading "actions/checkout" version for ubuntu-20.04/22.04.
- I will get the errors as shown below because of GLIBC if I upgrade "actions/checkout" version for ubuntu-18.04/centos. Now I don't know how to solve it
- Sometimes there are differences in different versions of the same system. I think more testing is better.
- I'm not very good at Windows, maybe I'll try to support it in the future
Snipaste_2024-04-12_14-43-50

**Comment by wolkykim** [comment]
Thank you for your contribution!

**Pull request merged**
