### PR TITLE
Should use qhasharr_remove_by_idx() after get_idx()

### PR DESCRIPTION
**Pull request by darkdh**
We should  use qhasharr_remove_by_idx() after getting idx from get_idx() instead.
Or we will call get_idx() again in qhasharr_remove()

### CODE REVIEW

**Comment by wolkykim** [comment]
Thanks. It's a nice catch.
I can't auto merge due to updates, would you please send me  pull request again after sync up?

**Comment by darkdh** [comment]
I merged my branch with the latest update.

**Comment by wolkykim** [comment]
Thank you.

**Comment by darkdh** [comment]
:)

**Pull request merged**
