### PR TITLE
hasharr binary key type

### PR DESCRIPTION
**Pull request by darkdh**
1. Add put(), get(), remove() operated by key object.
2. _print_key() for debug key print. If key is not string it will print hex value.
3. printobj() for printing object from getnext().
4. Modified hasharr example

### CODE REVIEW

**Comment by wolkykim** [comment]
I think we need to think about this if we really want to support binary object key type.
Because that hasharr, hashtbl and listtbl use consistent API to make it easier interchangable and all takes string type key. If we allow this in hasharr, then eventually we'll want to make others to have same api.

I recall this now, I was having hard time to decide whether to make it take binary key or string key in the default API and I decided to go with string key to practically make it easier.

I think I need to think about this again.
What do you think? Is it critical using binary key to your application?

**Comment by darkdh** [comment]
I must use binary key hash for my project because the unique id of X509 certificate is binary format. If I convert to hex string, it will cost me twice space to store a key and also inefficient. 

I chose hasharr as my container because the flexible slots arrangement and urgent need for memory-file hash table. The data I cached is whole X509 certificate so I must manage the space usage discreetly for caching more certificate.

Besides, the collision rate of  string hashing is higher than binary hashing. Think about the string is limited to only printable characters so the variety of input data for hash is shrunk.

**Comment by wolkykim** [comment]
I see your need.

> If I convert to hex string, it will cost me twice space to store a key and also inefficient. 
Actually, this is not true in qhasharr. qhasharr always use fixed lenth key size. 
If you see the slot definition, you'll notice key is always _Q_HASHARR_KEYSIZE length long.
If key is longer than that, it will store only the prefix of the key as long as it can store then store md5 value for the entire key. For lookup, it tries to match the prefix and md5.

So using longer key doesn't consume any more bytes in qhasharr. This idea is to help qhasharr to work in tight memory space more efficiently.

        struct _Q_HASHARR_SLOT_KEYVAL {
            unsigned char value[_Q_HASHARR_VALUESIZE];  /*!< value */

            char key[_Q_HASHARR_KEYSIZE];  /*!< key string, can be cut */
            uint16_t  keylen;              /*!< original key length */
            unsigned char keymd5[16];      /*!< md5 hash of the key */
        } pair;

We use murmur3 hash algorithm, it's a good algorithm that nicely implements major 3 principals of hash algorithm as well as speed. So the collision rate should not vary no matter it's 1 bit change or thousands bytes changes.

**Comment by darkdh** [comment]
Thank you for your detail description. I got what you said. Maybe I should reconsider my own design.

By the way, truncated key reminds me the _get_idx().
When it encounter the truncated key it compare the _Q_HASHARR_KEYSIZE of key and the md5 hash of key. I'm wondering whether this really guarantee they are the same key and no false positive.

Base on my concern, I use md5 to shrink my key to fixed size before putting it into hash table.

**Comment by wolkykim** [comment]
>  I'm wondering whether this really guarantee they are the same key and no false positive.
Yes, in theory there's a chance but in practice with given number of dataset, the chance is almost zero in practice. Using MD5 alone is not safe enough but combining the original key and original key size check will decrease the chance further down.

In many de-duplication filesystem use similar technique to calculate block's fingerprint, most of them use combination of 2 different types of hash algorithm. usually one is SHA1 and the other in their choice. I worked in that area before so I know some of those math. Considering the size of data set in qhasharr, I felt MD5 + origin key prefix comparison is sufficient without compromising too much of memory and speed.

Best approach for using binary key would be using non-digest base string conversion such as base64(1.5x size of original) because if you run digest on keys before putting it into table then you take the responsibility that the digested string matches the original key 1:1 in a data set.

For peace of mind. SHA1 128bit is complexer and practically faster on most of modern CPUs due to the algorithm allows parallel calculation and as we talked, key size doesn't cost much in qhasharr in terms of storage needs.

This is a nice conversation. Changing the underlying code of qhasharr to binary key base is bit complexer than code itself, The code needs to assume everything in binary, so no human readable keys in debug as well. I think it has pros and cons. I'm quite sure at this point and would like to take some more time to think about it. Current patch breaks back-ward compatibility so if want to go, we would want your previous patch. 

Besides of this, would you like to submit your unit tests on qhasharr?

**Comment by darkdh** [comment]
Thanks for your patience of explanation. I appreciate it. You are really good at this area. 

I will submit the unit test branch after work.

Besides, should I reopen the previous pull request which contains operations by object and separate the unit test?

**Comment by darkdh** [comment]
Thanks for your patience of explanation. I appreciate it. You are really good at this area. 

I will submit the unit test branch after work.

Besides, should I reopen the previous pull request which contains operations by object and separate the unit test?

**Comment by darkdh** [comment]
Maybe I should use base64 to encode my binary key as my hash table key. And we do need to support another API for binary key insertion and deletion. What do you think?

**Comment by darkdh** [comment]
And I finally remember why I can't use truncated key.
I cleanup my hash table by timeout. I add a time stamp for each slot. And I check it outside the library.
When I found some data has been timeout, I need to obtain the original key to perform remove.
However, the key I got from getnext() is truncated unless inside library timeout checking. In that case, we won't need a key to index slot but required more changes.

**Comment by wolkykim** [comment]
Good point. We can expose remove_by_idx() which is _remove_data() internal api. So the truncated key data can be removed in getnext() loop. I'll work on that.

**Comment by wolkykim** [comment]
> Besides, should I reopen the previous pull request which contains operations by object and separate the unit test?

I can reopen it when needed but would be nice if you can cut a separate one for the unit tests for one click merging.

**Comment by darkdh** [comment]
I have commit a new branch for hasharr unit test.

And I look forward to your exported remove_by_idx() API.

**Comment by wolkykim** [comment]
> And I'm looking forward to your exported remove_by_idx() API. 

It's done! 5122f6b1e6b196d421098e5058916e109f473afc

**Comment by darkdh** [comment]
That's cool. Thanks.

**Comment by wolkykim** [comment]
Hi, the patch has ported. Please see b4c1eeb453a4c9a482a528e6aa9533df633831e3

**Pull request closed without merging**
