### PR TITLE
Add unit test for hasharr

### PR DESCRIPTION
**Pull request by darkdh**
1. add 5 new macro
2. add test_qhasharr to Makefile
3. few simple unit tests

### CODE REVIEW

**Comment by wolkykim** [comment]
I've merged it into master 4477ad702c03a07785276802abca3f0e57dc5450
Thank you so much.

**Comment by darkdh** [comment]
Would you change the state of this pull request to "Merged" just like the previous one you merged?
Thank you.

**Comment by wolkykim** [comment]
Actually I was looking for a way to change the status to merged, so your contribution effort is logged permanently. Do you know how to do it? I had to run manual merge due to some code committed after your patch so auto merge was not possible option.

**Comment by wolkykim** [comment]
I ran git commit --amend, please check 17ea53959619a091a74bb08be9c1770de6ae18d5
Did you remove your branch already? I can't reopen. It seems this is pretty much we can do now. I doesn't increase your commit count but we have logs in the system. Next time I'll make sure this not to happen.

**Comment by darkdh** [comment]
I restored my branch. Let's try it again.

**Comment by wolkykim** [comment]
Upon your request, I tried it again hardly. I reopened it but only manualy merge is my option here.
I was redoing manual merge even the code is actually merged already but it seems it will result same so I stopped there. Would you like to pull the master and add or update the tests then send pull request?

**Comment by darkdh** [comment]
OK, I will pull and update the pull request.

**Comment by darkdh** [comment]
We should leverage the API:  qhasharr_calculate_memsize() to calculate the memory size by slots.
Many users will be confused by which size of memory should I allocate for hasharr witout knowing the internal structure. And I thought it's our responsibility to demostrate the subtle way to initialize a hasharr.

**Comment by wolkykim** [comment]
agree

**Comment by darkdh** [comment]
Thanks

**Pull request merged**
