### PR TITLE
Add ctest, update testing and building docs

### PR DESCRIPTION
**Pull request by netpoetica**
- addresses integrating qunit.h and ctest/cmake to make it easier to encourage writing unit tests https://github.com/wolkykim/qlibc/issues/3
- updates documention in INSTALL.md to avoid error on Mac OSX (https://github.com/wolkykim/qlibc/issues/10). Note: I left the old documentation because it seems like there is still some useful info in there. Let me know if the team thinks I should remove this.
- fix root endforeach varname typo …
- add ctest suite @demitsuri Please review and let me know what you think!
- add test fixtures dir. This directory can contain useful files for working with unit tests
- add .a and .dylib to .gitignore
- update readme howto run tests
- update install to prefer cmake

### CODE REVIEW

**Comment by demitsuri** [comment]
I think that it's too early to merge this code into the main branch.

Your contribution is very useful, but we'll have a number of promlems with two parralel versions of cmake buildscript. The most relevant version of cmake buildscript is here: https://github.com/demitsuri/qlibc/commit/cb971dd05ac0953bfcdd7f568b39915db49b6a1f

I merged your branch and after resolving conflics it looks very nice: https://github.com/demitsuri/qlibc/commit/4363171d09b5d0cf14589f0f24be3c959588fa25
Travis-CI result is here: https://travis-ci.org/demitsuri/qlibc/builds/48235447

I propose to merge it into features/port_windows branch for now, and merge back after completing development there.

**Comment by netpoetica** [comment]
Very cool that it's passing in Travis and also that `make test` is operational - thanks for catching that typo as well! I see, the port_windows branch does have quite a bit of difference from master.

If you're open to merge it with port_windows, then when I write some more unit tests I can either 1) send a PR to your port_windows branch so it integrates with ctest or 2) commit unit tests directly to master, running them manually, and eventually when we merge this ctest integration, it will pick up unit tests automatically.

One other thing I wanted to mention - how do you feel about doing a build inside of a .gitignored build/ directory within the repo, so that we don't have the convoluted process of mkdir, cd, send patch to sourcedir - would be great to be able to tell people "clone the repo and run `cmake . && make && make test`, knowing that qlibc will not leave footprints in project dir.

One more other thing - notice that the original qunit.js allows the user to write multiple tests in one file. CTest doesn't output each individual test, it treats each executable as a test. So, if you have a test_qcount executable with 50 tests cases in it, and 1 of those cases inside the executable fails, CTest thinks the test (added by ADD_TEST) fails. This seems reasonable enough to me but I am just wondering if anyone is really tied to the style of output from qunit.js?

**Comment by demitsuri** [comment]
I already merged this PR and port_windows branch. Result you can see here: https://github.com/demitsuri/qlibc/tree/netpoetica-add-ctest
You can send any updating PR into this branch. And I think we'll merge it into master branch in 3-4 days. I'm using git flow (http://danielkummer.github.io/git-flow-cheatsheet/index.tr_TR.html). You also can try to use this helpful extension.

Idea with gitignored CMakeCache.txt and CMakeFiles folder is great! This contribution can be sent as PR into the main branch directly.

We are not tied to the the style of output from qunit.h. But it can be very useful when degradation bug appears. You can suggest any kind of (code?) style for unit tests and we'll discuss it. At this point I don't unerstand what troubles can be caused by CTest and qunit.h.

Thank you for your activity!

**Comment by demitsuri** [comment]
I close this PR due to it's already merged to another branch.

**Comment by wolkykim** [comment]
Seems I am catching up too slow but glad to see you guys are getting feedback from each other.

**Comment by wolkykim** [comment]
netpoetica, qunit.js? do you mean qunit.h? To a library like qlibc, I think test must be 100% passing always so   treating one single failure out of thousands as a whole test fail is OK from that perspective as long as it logs enough to debug where the fail happens. But improvements are always good thing :) if i'm understanding what you meant differently please explain details.

**Comment by netpoetica** [comment]
Hey @wolkykim, yeah I meant qunit.h sorry :) mostly a JS dev and have woked with qunit.js a lot so I just mistyped.

I agree with you about the testing situation - I think with the way it is at the moment, each ctest represents "all tests for module n", where module n is each .c file and 1 or more tests for that module. Currently, what is happening is that even if you have let's say 10 tests a file qcount.c, when it's passing you will only know that the entire module passes (aka you will get 1 pass, even though all tests in that module passed), and when any individual tests in that module fails, you will get output about where the test failed in the module, but the whole module counts as a fail rather than just the one test.

I also think this is OK but I will keep in mind possibilities for potentially treating each individual item as it's own test, if I can come up with a way to use qunit.h and CTest in such a way.

Thanks!

**Comment by wolkykim** [comment]
I see what you mean. That's a good point. There is a bigger mistake actually that I made which is I didn't write the unit tests when I'm writing codes. And the amount of codes has been growing.

I don't think we need to make complete unit tests at this point but make essential parts such as containers. I think rough unit tests can be made up by referring examples and polished/expanded as time goes by.

This project needs someone to drive that part. It is wide open to somebody talented and detailed like you.

**Comment by netpoetica** [comment]
@wolkykim Thanks for the kind comments! I am currently working on putting together the tests - I have a lot of interest in this. I am going to start with containers, based on your direction and the fact that it appears they are sort of the meat and potatoes of qlibc. I have started a [new branch](https://github.com/netpoetica/qlibc/tree/feature/add-container-tests) which I will keep in sync with demitsuri's branch and eventually PR - added some recursion to the test script as well so that we can organize tests into similar folder structure like you have in include/ and src/ - will keep pushing at this and hopefully I can keep up with the growing codebase :)

**Comment by netpoetica** [comment]
Also, I do have some questions about qunit.h - I've never seen C code like this where there is this sort of dynamic construction of `main` - if you have time, a brief explanation of what's going on in there and maybe pointer to something I can read that might help me grok it, would love to be able to upgrade the test suite as needed. No rush, a general "what's goin on" would definitely be helpful :-) cheers

**Comment by demitsuri** [comment]
@netpoetica  That's easy. `qunit.h` creates a single function `main()` and pass all tests inside it.
`QUNIT_START` generates the head of this function. 
After that you should use `TEST` macro, that calculates result of the previous test (if any) and prints a header for the current test. 
Later use one or more `ASSERT`'s that just calculate is test failed. `ASSERT` does not return from the main function.
In the end use `QUNIT_END` macro for calculating result of the last test, prints summary and returns non-zero if one or more tests failed.

**Pull request closed without merging**
