### PR TITLE
Add continuous integration to automatically run tests

### PR DESCRIPTION
**Pull request by Fullaxx**

### CODE REVIEW

**Comment by wolkykim** [comment]
Thanks for the PR. Is this PR complete or is there any on-going work to add?

**Comment by Fullaxx** [comment]
No extra work at the moment. This will allow github to automatically run the test cases described in the yml file upon every git push.

Once this happen, I was going to suggest adding a badge to the README.md so that everyone can see that every code push passes test cases.  Here is the badge that can be added to README.md:
[Actions Status](https://github.com/wolkykim/qlibc/actions)

See example here:
https://github.com/Fullaxx/chronoqueue

**Comment by Fullaxx** [comment]
sorry the other update to the readme wasn't supposed to be in there.
That should be a separate PR. I will redo this

**Comment by wolkykim** [comment]
Sounds good. This is great!

**Pull request closed without merging**
