### PR TITLE
Support PostgreSQL

### PR DESCRIPTION
**Pull request by SunBeau**

### CODE REVIEW

**Comment by wolkykim** [comment]
Hi SunBeam,


Would you please exclude doc updates from the PR and only include code
changes? Doc update is better to be done separately and I can handle it.

Thanks

**Comment by wolkykim** [comment]
It looks like there are many code duplications between mysql.c and pgsql.c.
What do you think about using #ifdef and keeping both codes in database.c?

**Comment by SunBeau** [comment]
Please check the new [PR](https://github.com/wolkykim/qlibc/pull/113)

**Comment by wolkykim** [comment]
I'm closing this PR for now as we are working on the replacement, #113

**Pull request closed without merging**
